"""Shared contract for logs generated by the collector."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from collector.utils.timestamp import format_iso8601, get_current_utc_timestamp


@dataclass
class Event:
    """A log event with a source, type, message, severity, and JSON-compatible metadata.

    Timestamps must be timezone-aware; serialized timestamps are always in UTC.
    """

    source: str
    event_type: str
    message: str
    timestamp: datetime = field(default_factory=get_current_utc_timestamp)
    severity: str = "info"
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.timestamp.tzinfo is None or self.timestamp.utcoffset() is None:
            raise ValueError("Event timestamp must be timezone-aware.")

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-compatible representation of the event."""
        return {
            "timestamp": format_iso8601(self.timestamp.astimezone(timezone.utc)),
            "source": self.source,
            "event_type": self.event_type,
            "message": self.message,
            "severity": self.severity,
            "metadata": self.metadata,
        }

    def to_json(self) -> str:
        """Serialize the event as JSON."""
        return json.dumps(self.to_dict())
