"""Defines sources of logs that will be used throughout SentinelSIEM

These sources provide a standardized way to classify the origin of security events generated by the collector framework.
"""


from enum import StrEnum


class LogSource(StrEnum):
    """Represents the supported log sources within SentinelSIEM.""" 

    SSH = "ssh"